# Generated by Django 5.0.6 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journal_entry_bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=200)),
                ('order_no', models.CharField(blank=True, max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.CharField(blank=True, max_length=200)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('Userlogin', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'journal_entry_bin',
            },
        ),
        migrations.CreateModel(
            name='loan_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debtor_name', models.CharField(max_length=200)),
                ('debtor_id', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=223)),
                ('amount_borrowed', models.CharField(max_length=200)),
                ('amount_paid', models.CharField(max_length=200)),
                ('balance_left', models.CharField(max_length=200)),
                ('account_debited', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, default='unpaid', max_length=200)),
                ('token_ID', models.CharField(blank=True, max_length=200)),
                ('transaction_id', models.CharField(editable=False, max_length=200)),
                ('Userlogin', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'loan_account',
            },
        ),
        migrations.CreateModel(
            name='loan_account_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debtor_name', models.CharField(max_length=200)),
                ('debtor_id', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=223)),
                ('amount_borrowed', models.CharField(max_length=200)),
                ('amount_paid', models.CharField(max_length=200)),
                ('balance_left', models.CharField(max_length=200)),
                ('account_debited', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, default='unpaid', max_length=200)),
                ('token_ID', models.CharField(blank=True, max_length=200)),
                ('transaction_id', models.CharField(editable=False, max_length=200)),
                ('Userlogin', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'loan_account_log',
            },
        ),
        migrations.CreateModel(
            name='new_journal_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=200)),
                ('order_no', models.CharField(blank=True, max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.CharField(blank=True, max_length=200)),
                ('credit', models.CharField(blank=True, max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(max_length=200)),
                ('token_ID', models.CharField(blank=True, max_length=200)),
                ('Userlogin', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'new_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='new_journal_entry_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=200)),
                ('order_no', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200)),
                ('total_debit', models.CharField(max_length=200)),
                ('total_credit', models.CharField(max_length=200)),
                ('token_ID', models.CharField(max_length=200)),
                ('Userlogin', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'new_journal_entry_log',
            },
        ),
        migrations.CreateModel(
            name='new_journal_entry_profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=200)),
                ('order_no', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('token_ID', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'new_journal_entry_profit',
            },
        ),
        migrations.CreateModel(
            name='new_journal_entry_profit_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_no', models.CharField(max_length=200)),
                ('order_no', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('narration', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('debit', models.CharField(max_length=200)),
                ('credit', models.CharField(max_length=200)),
                ('total_debit', models.CharField(max_length=200)),
                ('total_credit', models.CharField(max_length=200)),
                ('token_ID', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'new_journal_entry_profit_log',
            },
        ),
    ]
