# Generated by Django 5.0.6 on 2024-10-21 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.CharField(default='U2EnbbGxi9', max_length=255)),
                ('transaction_source', models.CharField(default='INTER ACCOUNT TRANSFER', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('token_id', models.CharField(default='8856757', max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('account_type', models.CharField(default='Cash', max_length=255)),
                ('dateTimeSt', models.DateTimeField(auto_now_add=True)),
                ('cancellation_status', models.CharField(default=0, max_length=255)),
                ('Userlogin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'account_log',
            },
        ),
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_series', models.CharField(max_length=255)),
                ('series_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(max_length=255)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('Userlogin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Assets_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('series_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('account_bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('canclelation_status', models.CharField(default='Inactive', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('Userlogin', models.CharField(blank='True', max_length=255, null='True')),
            ],
            options={
                'db_table': 'assets_account',
            },
        ),
        migrations.CreateModel(
            name='chart_of_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('series_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('account_bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('token_id', models.CharField(default='MlS0jAA0YV', max_length=255)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('cleared_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pending_deposit', models.CharField(blank=True, max_length=255, null=True)),
                ('pending_withdrawal', models.CharField(blank=True, max_length=255, null=True)),
                ('availablr_credit', models.CharField(blank=True, max_length=255, null=True)),
                ('Userlogin', models.CharField(blank='True', max_length=255, null='True')),
            ],
            options={
                'db_table': 'chart_of_account',
            },
        ),
        migrations.CreateModel(
            name='Equity_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('series_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('account_bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('canclelation_status', models.CharField(default='Inactive', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('Userlogin', models.CharField(blank='True', max_length=255, null='True')),
            ],
            options={
                'db_table': 'equity_account',
            },
        ),
        migrations.CreateModel(
            name='Expenses_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('series_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('account_bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('canclelation_status', models.CharField(default='Inactive', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('Userlogin', models.CharField(blank='True', max_length=255, null='True')),
            ],
            options={
                'db_table': 'expenses_account',
            },
        ),
        migrations.CreateModel(
            name='Income_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('series_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('account_bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('canclelation_status', models.CharField(default='Inactive', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('Userlogin', models.CharField(blank='True', max_length=255, null='True')),
            ],
            options={
                'db_table': 'income_account',
            },
        ),
        migrations.CreateModel(
            name='Liability_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('series_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('account_bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Inactive', max_length=255)),
                ('canclelation_status', models.CharField(default='Inactive', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('Userlogin', models.CharField(blank='True', max_length=255, null='True')),
            ],
            options={
                'db_table': 'liability_account',
            },
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'payment_method',
            },
        ),
        migrations.CreateModel(
            name='transfer_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tx', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('paid_from', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('received_in', models.CharField(max_length=255)),
                ('token_id', models.CharField(blank=True, default='9oXuARbWkC', max_length=12)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'transfer_account',
            },
        ),
    ]
