# Generated by Django 5.0.6 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(default='0', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cat_payment_method',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('state', models.IntegerField(default=0)),
                ('cat_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='category_img/')),
                ('token_id', models.CharField(blank=True, default='j5amD5DlPm', max_length=25)),
                ('Userlogin', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Check_StockLevel_By',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'check_stock_level_by',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('limit', models.CharField(max_length=100)),
                ('usage', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='couponUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('invoice', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='None', max_length=256)),
            ],
            options={
                'db_table': 'couponUsers',
            },
        ),
        migrations.CreateModel(
            name='CreateOutletStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetx', models.DateField(auto_now_add=True, max_length=222)),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=250)),
                ('warehouse', models.CharField(blank=True, max_length=250, null=True)),
                ('outlet', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('item_decription', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('token_id', models.CharField(max_length=250)),
                ('item_code', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('selling_price', models.CharField(max_length=250)),
                ('wholesale_price', models.CharField(max_length=250)),
                ('notification_status', models.CharField(max_length=250)),
                ('low_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('main', models.BooleanField(default=True)),
            ],
            options={
                'db_table': ' outlet_stockin',
            },
        ),
        migrations.CreateModel(
            name='CreateOutletStockInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetx', models.DateField()),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=250)),
                ('warehouse', models.CharField(blank=True, max_length=250, null=True)),
                ('outlet', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('item_decription', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('token_id', models.CharField(max_length=250)),
                ('item_code', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('selling_price', models.CharField(max_length=250)),
                ('wholesale_price', models.CharField(max_length=250)),
                ('status', models.CharField(default='Unverified', max_length=250)),
                ('edit_status', models.CharField(default='Unverified', max_length=250)),
                ('transfer', models.CharField(blank=True, max_length=200, null=True)),
                ('ref_no', models.CharField(max_length=250)),
                ('main', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'outlet_stockin_log',
            },
        ),
        migrations.CreateModel(
            name='CreateStockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetx', models.DateField(auto_now_add=True, max_length=222)),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=250)),
                ('warehouse', models.CharField(max_length=250)),
                ('outlet', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('item_decription', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('manufacture_date', models.DateField(auto_now_add=True, max_length=250, null=True)),
                ('expiry_date', models.DateField(auto_now_add=True, max_length=250, null=True)),
                ('Notification_date', models.DateField(auto_now_add=True, max_length=250, null=True)),
                ('notification_status', models.CharField(max_length=250)),
                ('low_stock_level', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('token_id', models.CharField(max_length=250)),
                ('item_code', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('main', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'stockin',
            },
        ),
        migrations.CreateModel(
            name='CreateStockInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetx', models.DateField(auto_now_add=True, max_length=250)),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('supplier', models.CharField(max_length=250)),
                ('warehouse', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(max_length=250)),
                ('item_decription', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('outlet', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(max_length=250)),
                ('manufacture_date', models.DateField(auto_now_add=True, max_length=250, null=True)),
                ('expiry_date', models.DateField(auto_now_add=True, max_length=250, null=True)),
                ('Notification_date', models.DateField(auto_now_add=True, max_length=250, null=True)),
                ('notification_status', models.CharField(max_length=250)),
                ('token_id', models.CharField(max_length=250)),
                ('item_code', models.CharField(max_length=250)),
                ('ref_no', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('status', models.CharField(default='Unverified', max_length=250)),
                ('transfer', models.CharField(blank=True, max_length=200, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stockin_log',
            },
        ),
        migrations.CreateModel(
            name='CreateStockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, max_length=250)),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('customer', models.CharField(max_length=250)),
                ('warehouse', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('item_description', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('stockout_status', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'stockout',
            },
        ),
        migrations.CreateModel(
            name='CreateStockoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, max_length=250)),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('customer', models.CharField(max_length=250)),
                ('warehouse', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('item_code', models.CharField(max_length=250)),
                ('item_description', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('stockout_status', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'stockout_order',
            },
        ),
        migrations.CreateModel(
            name='fre_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('state', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'fre_category',
            },
        ),
        migrations.CreateModel(
            name='fre_item_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256)),
                ('state', models.IntegerField(default=0)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'fre_item_table',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('generated_code', models.CharField(max_length=255)),
                ('purchase_price', models.CharField(max_length=255)),
                ('selling_price', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('wholesale_price', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=255)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_img/')),
                ('availability', models.IntegerField(default=1)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=65)),
                ('token_id', models.CharField(default='2vWNnW8SJY', max_length=255)),
                ('Userlogin', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('qty_state', models.CharField(default='Quantify', max_length=255)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemBrand',
            },
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('color_name', models.CharField(blank=True, max_length=255, null=True)),
                ('color_code', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemColor',
            },
        ),
        migrations.CreateModel(
            name='ItemCustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemCustomerReview',
            },
        ),
        migrations.CreateModel(
            name='ItemDetailDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemDetailDescription',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_img/')),
            ],
            options={
                'db_table': 'item_image',
            },
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemSize',
            },
        ),
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemSpecification',
            },
        ),
        migrations.CreateModel(
            name='ItemSpecificationFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('key_features', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemSpecificationFeatures',
            },
        ),
        migrations.CreateModel(
            name='ItemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ItemTags',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetx', models.DateField(auto_now_add=True, max_length=222)),
                ('invoice_no', models.CharField(blank=True, max_length=250, null=True)),
                ('initial_qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('new_qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('item_code', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'stock_adjustment_log',
            },
        ),
        migrations.CreateModel(
            name='StockInUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
                ('oldQty', models.CharField(max_length=250)),
                ('newQty', models.CharField(max_length=250)),
                ('user', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'stockin_update_log',
            },
        ),
        migrations.CreateModel(
            name='StockOutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetx', models.DateField(auto_now_add=True, max_length=222)),
                ('invoice_no', models.CharField(max_length=250)),
                ('order_no', models.CharField(max_length=250)),
                ('customer', models.CharField(max_length=250)),
                ('warehouse', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('item', models.CharField(max_length=250)),
                ('item_description', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('token', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('stockout_status', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'stockout_log',
            },
        ),
        migrations.CreateModel(
            name='StockOutStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('userlogin', models.CharField(max_length=250)),
                ('token_id', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'stockout_status',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
    ]
