# Generated by Django 5.0.6 on 2024-10-21 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusers',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fre_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='customer_likes', to='customer.customer_table'),
        ),
        migrations.AddField(
            model_name='fre_item_table',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.item'),
        ),
        migrations.AddField(
            model_name='itemcustomerreview',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer_table'),
        ),
        migrations.AddField(
            model_name='itemcustomerreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.item'),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_items', to='Stock.itemtags'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.sub_category'),
        ),
    ]
