# Generated by Django 5.0.6 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('company_db', models.CharField(max_length=256)),
                ('company_db_pass', models.CharField(blank=True, max_length=256)),
                ('company_db_user', models.CharField(max_length=256)),
                ('address', models.CharField(default='none', max_length=256)),
                ('phone', models.CharField(default='none', max_length=256)),
                ('email', models.CharField(default='none', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_companies',
            },
        ),
        migrations.CreateModel(
            name='shipping_addr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'shipping_addr',
            },
        ),
    ]
