"""
Django settings for Afrikbook_proj project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from django.conf.global_settings import AUTHENTICATION_BACKENDS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bdad%tpby&zszmtofy=7ye6o2@98!=9#lq4tqy)$h&gz+x#&$-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'isdoremartins23@gmail.com'
EMAIL_HOST_PASSWORD = 'etwkejogsyfimzbi'
# EMAIL_PORT = 587
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True # CHANGE EMAIL_USE_TLS = False

EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND= 'django.core.mail.backends.console.EmailBackend'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'django.contrib.reportlab',

    # my apps
    'main',
    'customer',
    'settings',
    'employee',
    'journal',
    'report',
    'filter',
    'vendor',
    'account',
    'widget',
    'Stock',
    'Stockin',
    'basic_sales_app',
    'client',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Afrikbook_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Afrikbook_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgres',
#         'NAME': BASE_DIR / 'db.postgres',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'afrik_database',
#         'USER': 'root',
#         'HOST': '127.0.0.1',
#         'PASSWORD': '',
#         'PORT': '3306' ,
#     },
    
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Afrikbook_db',
        'USER': 'Afrikbook',
        'PASSWORD': 'afrik',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "static/"] 

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

STATIC_ROOT = BASE_DIR /'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# lily settings configuration
MY_EXPERIMENT = True




# bright settings configurations

AUTH_USER_MODEL = 'main.User'

AUTHENTICATION_BACKENDS = {
    "main.backends.EmailAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend"
}





# DATABASES['afrikbook_client'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_client', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 

# DATABASES['afrikbook_5862'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_5862', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 

# DATABASES['afrikbook_9521'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_9521', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_4375'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_4375', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 

# DATABASES['afrikbook_9677'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_9677', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_5542'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_5542', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_5320'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_5320', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_2826'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_2826', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_8432'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_8432', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_0372'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_0372', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_6113'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_6113', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_7129'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_7129', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_1495'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_1495', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_4782'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_4782', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 


# DATABASES['afrikbook_3175'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_3175', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
# DATABASES['afrikbook_5413'] = {
#   'ENGINE': 'django.db.backends.mysql',
#   'NAME':  'afrikbook_5413', 
#   'USER':  'root',
#   'PASSWORD': '',
#   'HOST': 'localhost',
#   'PORT': '3306',
# } 
DATABASES['afrikbook_4289'] = {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'afrikbook_4289', 
  'USER': 'Afrikbook',
  'PASSWORD': 'afrik',
  'HOST': 'localhost',
  'PORT': '5432',
}
DATABASES['afrikbook_3110'] = {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'afrikbook_3110', 
  'USER': 'Afrikbok',
  'PASSWORD': 'afrik',
  'HOST': 'localhost',
  'PORT': '5432',
}
DATABASES['afrikbook_6814'] = {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'afrikbook_6814', 
  'USER': 'Afrikbook',
  'PASSWORD': 'afrik',
  'HOST': 'localhost',
  'PORT': '5432',
}
DATABASES['afrikbook_5013'] = {
  'ENGINE': 'django.db.backends.postgresql',
  'NAME': 'afrikbook_5013', 
  'USER': 'Afrikbook',
  'PASSWORD': 'afrik',
  'HOST': 'localhost',
  'PORT': '5432',
}