# Generated by Django 5.0.6 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('db_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('token_id', models.IntegerField(blank=True, null=True)),
                ('Userlogin', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
