# Generated by Django 5.0.6 on 2024-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=222)),
                ('email', models.EmailField(max_length=225)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=225)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widow/Widower', 'Widow/Widower')], max_length=255)),
                ('address', models.CharField(max_length=222)),
                ('staff_ID', models.CharField(blank=True, max_length=255, unique=True)),
                ('basic_salary', models.CharField(max_length=223)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], max_length=255)),
                ('supervisor', models.CharField(max_length=222)),
                ('start_date', models.DateField()),
                ('work_location', models.CharField(max_length=222)),
                ('token_id', models.CharField(blank=True, max_length=222, null=True)),
                ('Userlogin', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='employee_account_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255)),
                ('account_no', models.CharField(max_length=222)),
                ('account_name', models.CharField(max_length=222)),
                ('bank_name', models.CharField(max_length=222)),
            ],
            options={
                'db_table': 'employee_account_details',
            },
        ),
        migrations.CreateModel(
            name='employee_guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_fullname', models.CharField(max_length=222)),
                ('residential_address', models.CharField(max_length=222)),
                ('work_address', models.CharField(max_length=222)),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Friend', 'Friend')], max_length=255)),
                ('g_phone', models.CharField(max_length=225)),
                ('g_email', models.EmailField(max_length=225)),
                ('employee_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee_guarantor',
            },
        ),
        migrations.CreateModel(
            name='payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=222)),
                ('employee_name', models.CharField(max_length=255)),
                ('staffID', models.CharField(max_length=200)),
                ('bsaic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('overtime', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('others', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('loan_repay', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('union_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('sanction', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('NHF', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('NSIFT', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('total_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('token_id', models.CharField(blank=True, max_length=200, null=True)),
                ('Userlogin', models.CharField(blank=True, max_length=60, null=True)),
                ('dateG', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='unapprove', max_length=60)),
                ('confirm_payment', models.CharField(default='pending', max_length=60)),
            ],
            options={
                'db_table': 'payroll',
            },
        ),
        migrations.CreateModel(
            name='payroll_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=225)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('status', models.CharField(default='unapprove', max_length=60)),
                ('account_debited', models.CharField(max_length=225)),
                ('token_id', models.CharField(blank=True, max_length=60)),
                ('Userlogin', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'db_table': 'payroll_log',
            },
        ),
        migrations.CreateModel(
            name='staff_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('initial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=64, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=50)),
                ('staff_name', models.CharField(blank=True, max_length=60)),
                ('payment_method', models.CharField(max_length=50)),
                ('cur_datetime', models.DateTimeField(auto_now_add=True)),
                ('account_posted', models.CharField(blank=True, max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('token_id', models.CharField(blank=True, max_length=50)),
                ('Userlogin', models.CharField(blank=True, max_length=50)),
                ('invoice_status', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'staff_account',
            },
        ),
    ]
