# Generated by Django 5.0.6 on 2024-10-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0001_initial'),
        ('Stockin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addressShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(default='none', max_length=256)),
                ('item_name', models.CharField(default='none', max_length=256)),
                ('generated_code', models.CharField(default='none', max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
            ],
            options={
                'db_table': 'addressshippingprice',
            },
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='CreateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerName', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('phone2', models.CharField(blank=True, max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('Rc', models.CharField(blank=True, max_length=250)),
                ('CompanyName', models.CharField(max_length=250)),
                ('services', models.TextField(blank=True, max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('show_customer_info', models.CharField(blank=True, max_length=250, null=True)),
                ('Token_ID', models.CharField(blank=True, max_length=250, null=True)),
                ('vat', models.CharField(blank=True, max_length=250, null=True)),
                ('Userlogin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='ExpiryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('item_code', models.CharField(blank=True, max_length=250, null=True)),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('days', models.CharField(blank=True, max_length=250, null=True)),
                ('Userlogin', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'ExpiryDate',
            },
        ),
        migrations.CreateModel(
            name='pickupstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'pickupstation',
            },
        ),
        migrations.CreateModel(
            name='pricechange_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=233)),
                ('productname', models.CharField(max_length=233)),
                ('purchaseprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('initial_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_sellingprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'pricechange_history',
            },
        ),
        migrations.CreateModel(
            name='sales_outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_name', models.CharField(max_length=233, unique=True)),
                ('phone', models.CharField(max_length=233)),
                ('address', models.CharField(max_length=233)),
                ('country', models.CharField(max_length=233)),
                ('currency', models.CharField(blank=True, max_length=233)),
                ('Userlogin', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'sales_outlet',
            },
        ),
        migrations.CreateModel(
            name='SalesInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('business_type', models.CharField(blank=True, max_length=250, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('Userlogin', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'sale_interface',
            },
        ),
        migrations.CreateModel(
            name='shipping_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceID', models.CharField(default='none', max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('custID', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipping_cost',
            },
        ),
        migrations.CreateModel(
            name='shipping_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'shipping_method',
            },
        ),
        migrations.CreateModel(
            name='user_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=250)),
                ('outlet', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('account_type', models.CharField(max_length=100)),
                ('token_ID', models.CharField(default='7D7Vq78Cfw', max_length=12)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(default='7750849', max_length=255)),
                ('token_id', models.CharField(default='nHs7TXiiFY', max_length=255)),
                ('Userlogin', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
                ('detail', models.CharField(max_length=250)),
                ('Userlogin', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stockin.company_table')),
            ],
            options={
                'db_table': 'Company_details',
            },
        ),
        migrations.CreateModel(
            name='pickUpShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('generated_code', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.pickupstation')),
            ],
            options={
                'db_table': 'pickUpshippingprice',
            },
        ),
        migrations.CreateModel(
            name='SetItemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_days', models.IntegerField(default=0)),
                ('Userlogin', models.CharField(blank=True, max_length=250, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.item')),
            ],
            options={
                'db_table': 'SetItemNotification',
            },
        ),
    ]
